# Don't do it, unless the memory usage doesn't matter!!!
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
